/**
 * Knowledge Base Writer — writes agent findings to the local KB repository.
 *
 * Target: /Users/jamestunick/Documents/GitHub/Unity-XR-AI/KnowledgeBase/
 * Convention: Files named _TOPIC_NAME.md (uppercase with underscores)
 * Auto-commits changes to git with descriptive messages.
 *
 * Exports:
 *   writeToKB(topic, content, options)   — Create or overwrite a KB file
 *   appendToKB(filename, section, content) — Append to an existing KB file
 *   listKBFiles()                          — List all KB files
 */
import fs from "node:fs";
import path from "node:path";
import { execSync } from "node:child_process";
import { memoryRead, memoryWrite } from "./shared-memory.mjs";

// ─── Constants ───

const KB_DIR = "/Users/jamestunick/Documents/GitHub/Unity-XR-AI/KnowledgeBase";
const KB_WRITE_LOG_KEY = "kb-write-log";
const MAX_WRITE_LOG = 100; // track last 100 writes

// ─── Helpers ───

/**
 * Convert a topic string into the KB filename convention: _TOPIC_NAME.md
 * e.g. "Agent Learning Patterns" -> "_AGENT_LEARNING_PATTERNS.md"
 */
function topicToFilename(topic) {
  const normalized = topic
    .toUpperCase()
    .replace(/[^A-Z0-9\s_]/g, "")
    .replace(/\s+/g, "_")
    .replace(/_+/g, "_")
    .replace(/^_|_$/g, "");
  return `_${normalized}.md`;
}

/**
 * Generate metadata header for new KB files.
 */
function generateHeader(topic) {
  const date = new Date().toISOString().split("T")[0];
  return [
    `<!-- Generated by XRAI Agent System, ${date} -->`,
    `# ${topic}`,
    "",
    `**Generated**: ${date}`,
    `**Source**: XRAI Agent Ecosystem (auto-generated)`,
    "",
    "---",
    "",
  ].join("\n");
}

/**
 * Record a write action to shared memory for tracking.
 */
function logWrite(action, filename, details) {
  const log = memoryRead(KB_WRITE_LOG_KEY) || [];
  log.push({
    action,
    filename,
    timestamp: new Date().toISOString(),
    ...details,
  });
  // Keep only the most recent entries
  const trimmed = log.length > MAX_WRITE_LOG ? log.slice(-MAX_WRITE_LOG) : log;
  memoryWrite(KB_WRITE_LOG_KEY, trimmed);
}

/**
 * Run a git command in the KB directory. Returns output or null on failure.
 */
function gitCommand(cmd) {
  try {
    return execSync(cmd, {
      cwd: KB_DIR,
      stdio: "pipe",
      timeout: 15000,
    }).toString().trim();
  } catch (err) {
    return null;
  }
}

/**
 * Auto-commit KB changes with a descriptive message.
 */
function autoCommit(filename, action) {
  const commitMsg = `[XRAI Agent] ${action}: ${filename}`;
  gitCommand(`git add "${filename}"`);
  const result = gitCommand(`git commit -m "${commitMsg.replace(/"/g, '\\"')}"`);
  return result !== null;
}

// ─── Exports ───

/**
 * Write a new KB file or overwrite an existing one.
 *
 * @param {string} topic — Human-readable topic name (e.g. "Agent Learning Patterns")
 * @param {string} content — Markdown content to write
 * @param {Object} [options]
 * @param {boolean} [options.overwrite=false] — Overwrite if file exists (default: refuse)
 * @param {boolean} [options.autoCommit=true] — Auto-commit to git
 * @param {boolean} [options.includeHeader=true] — Include metadata header
 * @param {string} [options.filename] — Override auto-generated filename
 * @returns {Object} Result with status, path, filename
 */
export function writeToKB(topic, content, options = {}) {
  if (!topic || !content) {
    return { error: "Both 'topic' and 'content' are required." };
  }

  if (!fs.existsSync(KB_DIR)) {
    return { error: `KB directory not found: ${KB_DIR}` };
  }

  const filename = options.filename || topicToFilename(topic);
  const filePath = path.join(KB_DIR, filename);
  const overwrite = options.overwrite === true;
  const shouldCommit = options.autoCommit !== false;
  const includeHeader = options.includeHeader !== false;

  // Check if file exists
  if (fs.existsSync(filePath) && !overwrite) {
    return {
      error: `File already exists: ${filename}. Use overwrite:true or appendToKB() instead.`,
      existingFile: filename,
      path: filePath,
    };
  }

  // Build file content
  let fullContent;
  if (includeHeader) {
    fullContent = generateHeader(topic) + content;
  } else {
    fullContent = content;
  }

  // Ensure trailing newline
  if (!fullContent.endsWith("\n")) fullContent += "\n";

  // Write the file
  fs.writeFileSync(filePath, fullContent, "utf-8");

  // Auto-commit
  let committed = false;
  if (shouldCommit) {
    committed = autoCommit(filename, fs.existsSync(filePath) ? "Update" : "Create");
  }

  // Log the write
  logWrite("write", filename, {
    topic,
    bytes: fullContent.length,
    overwrite,
    committed,
  });

  return {
    status: "written",
    filename,
    path: filePath,
    bytes: fullContent.length,
    committed,
  };
}

/**
 * Append content to an existing KB file under a section heading.
 *
 * @param {string} filename — KB filename (e.g. "_AGENT_LEARNING_PATTERNS.md")
 * @param {string} section — Section heading to add (e.g. "## New Findings")
 * @param {string} content — Content to append under the section
 * @param {Object} [options]
 * @param {boolean} [options.autoCommit=true] — Auto-commit to git
 * @param {boolean} [options.createIfMissing=false] — Create file if it doesn't exist
 * @returns {Object} Result with status
 */
export function appendToKB(filename, section, content, options = {}) {
  if (!filename || !content) {
    return { error: "Both 'filename' and 'content' are required." };
  }

  if (!fs.existsSync(KB_DIR)) {
    return { error: `KB directory not found: ${KB_DIR}` };
  }

  // Normalize filename — add _ prefix and .md suffix if missing
  if (!filename.startsWith("_")) filename = "_" + filename;
  if (!filename.endsWith(".md")) filename += ".md";

  const filePath = path.join(KB_DIR, filename);
  const shouldCommit = options.autoCommit !== false;

  // If file doesn't exist, optionally create it
  if (!fs.existsSync(filePath)) {
    if (options.createIfMissing) {
      // Derive topic from filename
      const topic = filename
        .replace(/^_/, "")
        .replace(/\.md$/, "")
        .replace(/_/g, " ")
        .split(" ")
        .map((w) => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
        .join(" ");
      const header = generateHeader(topic);
      fs.writeFileSync(filePath, header, "utf-8");
    } else {
      return {
        error: `File not found: ${filename}. Use createIfMissing:true or writeToKB() instead.`,
      };
    }
  }

  // Read existing content
  let existing = fs.readFileSync(filePath, "utf-8");

  // Build the append block
  const date = new Date().toISOString().split("T")[0];
  const appendBlock = [
    "",
    section ? `${section}` : "",
    section ? "" : "",
    `<!-- Appended by XRAI Agent, ${date} -->`,
    "",
    content,
    "",
  ]
    .filter((line) => line !== undefined)
    .join("\n");

  // Ensure existing ends with newline
  if (!existing.endsWith("\n")) existing += "\n";

  fs.writeFileSync(filePath, existing + appendBlock, "utf-8");

  // Auto-commit
  let committed = false;
  if (shouldCommit) {
    committed = autoCommit(filename, "Append");
  }

  // Log the write
  logWrite("append", filename, {
    section,
    appendedBytes: appendBlock.length,
    committed,
  });

  return {
    status: "appended",
    filename,
    path: filePath,
    appendedBytes: appendBlock.length,
    committed,
  };
}

/**
 * List all KB files with basic metadata.
 * @param {Object} [options]
 * @param {string} [options.filter] — Filter filenames containing this string (case-insensitive)
 * @returns {Object} List of KB files with names and sizes
 */
export function listKBFiles(options = {}) {
  if (!fs.existsSync(KB_DIR)) {
    return { error: `KB directory not found: ${KB_DIR}` };
  }

  let files;
  try {
    files = fs.readdirSync(KB_DIR).filter((f) => f.startsWith("_") && f.endsWith(".md"));
  } catch (err) {
    return { error: `Failed to read KB directory: ${err.message}` };
  }

  // Apply filter if provided
  if (options.filter) {
    const filterLower = options.filter.toLowerCase();
    files = files.filter((f) => f.toLowerCase().includes(filterLower));
  }

  // Gather metadata
  const result = files.map((f) => {
    const filePath = path.join(KB_DIR, f);
    try {
      const stat = fs.statSync(filePath);
      return {
        filename: f,
        sizeBytes: stat.size,
        modified: stat.mtime.toISOString(),
      };
    } catch {
      return { filename: f, sizeBytes: 0, modified: null };
    }
  });

  // Sort by modification time, newest first
  result.sort((a, b) => {
    if (!a.modified) return 1;
    if (!b.modified) return -1;
    return b.modified.localeCompare(a.modified);
  });

  return {
    count: result.length,
    directory: KB_DIR,
    files: result,
  };
}
